# (Makefile) ~ local configuration and overrides (* after basic functions/vars are defined)

# spell-checker:ignore (CC) lboost libboost multilib mthreads mwindows pthread struct Xclang Wlinker Wunknown
# spell-checker:ignore (make) addprefix CFLAGS CPPFLAGS CXXFLAGS ifeq ifneq LDFLAGS notdir
# spell-checker:ignore (vars) BASEPATH OSID

NAME := blat

SRC_PATH := src/blat $()## path to source relative to makefile (defaults to first of ['src','source']); used to create ${SRC_DIR} which is then used as the source base directory path
LIBS := advapi32 wsock32 $()## list of any additional required libraries (space-separated)

# * disable warnings
# # (bcc32) ## -w-NNNN :: disable warning WNNNN
# # ~ W8004 == VARIABLE is assigned a value that is never used ; W8057 == parameter is never used
# # ~ W8064 == call to function with no prototype ; W8065 == no prototype for function
# # ~ W8066 == unreachable code in function
# CFLAGS_bcc32 := -w-8004 -w-8057 -w-8064 -w-8065 -w-8066
CFLAGS_cl := $(if $(filter clang-cl,${CC}),-Wno-deprecated-non-prototype,)
CFLAGS_clang := -Wno-deprecated-declarations -Wno-format -Wno-ignored-attributes -Wno-keyword-macro -Wno-language-extension-token -Wno-misleading-indentation -Wno-parentheses-equality -Wno-self-assign -Wno-switch -Wno-tautological-constant-out-of-range-compare -Wno-unused-but-set-variable -Wno-writable-strings -Wno-language-extension-token -Wno-unused-but-set-parameter
CFLAGS_gcc := -Wno-deprecated-declarations -Wno-format -Wno-ignored-attributes -Wno-misleading-indentation -Wno-stringop-overflow -Wno-switch -Wno-unknown-pragmas -Wno-unused-but-set-variable -Wno-write-strings -Wno-type-limits -Wno-implicit-fallthrough -Wno-extra
